hetzner_instance_type: 'cx11'
hetzner_token: 'jCdAtSORfQKb7z5FHPxAU25txWT5zGyeqF71FS8aPj0QsNYNEy6oT5Q9SjzAXVDF'
hetzner_ssh_keys: ['enricobartz']
hetzner_worker_count: 5
hetzner_instance_os: 'centos-7'
hetzner_datacenter: 'nbg1-dc3'
