---
- hosts: kube-master
  remote_user: root
  roles:
    - rancher

- hosts: kube-worker-*
  remote_user: root
  tasks:
    - name: join the cluster
      shell: "{{ hostvars['kube-master']['cluster_command'] }} --worker"
