---
- name: 'cleanup conainers'
  shell: 'docker rm -f $(docker ps -aq) || true'

- name: 'cleanup images'
  shell: 'docker rmi -f $(docker images -q) || true'

- name: Remove Certificates
  file:
    path: '{{ item }}'  
    state: absent
  loop:
    - /var/lib/etcd
    - /etc/kubernetes
    - /etc/cni 
    - /opt/cni 
    - /var/lib/cni 
    - /var/run/calico 
    - /opt/rke

