---
- name: Install basic packages
  yum: state=present name={{ item }}
  with_items:
    - epel-release
    - screen
    - vim
    - openssl
    - net-tools
    - nmap
    - wget
    - curl
    - unzip
    - rsync
    - mlocate
    - telnet

- name: Install additional packages
  yum: state=present name={{ item }}
  with_items:
    - glances
    - htop
    - jq

- name: create rancher master container
  shell: 'docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher'

- name: create cluster init file
  template:
    src: 'cluster_init.sh.j2'
    dest: '/usr/local/bin/cluster_init.sh'
    owner: root
    mode: 0750

- name: get cluster setup command
  shell: '/usr/local/bin/cluster_init.sh'
  register: cluster_result

- name: set cluster_command fact
  set_fact: cluster_command={{ cluster_result.stdout }}

- name: join the master to the cluster
  shell: "{{cluster_command}} --etcd --controlplane"
