---
- name: 'install docker'
  shell: 'curl https://releases.rancher.com/install-docker/19.03.sh | sh'
  environment:
        HTTP_PROXY: '{{ vars.http_proxy }}'
        HTTPS_PROXY: '{{ vars.http_proxy }}'

- name: Install basic packages for Centos/Redhat
  yum: 
    state: present
    name: iscsi-initiator-utils
  environment:
        HTTP_PROXY: '{{ vars.http_proxy }}'
        HTTPS_PROXY: '{{ vars.http_proxy }}'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install basic packages Debian/Ubuntu
  apt: 
    state: present
    name: open-iscsi
  environment:
        HTTP_PROXY: '{{ vars.http_proxy }}'
        HTTPS_PROXY: '{{ vars.http_proxy }}'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Make sure Docker is running
  systemd:
    state: started
    enabled: yes
    name: docker
