---
- name: 'install docker'
  shell: 'curl https://releases.rancher.com/install-docker/18.09.sh | sh'

- name: Install basic packages
  yum: 
    state: present
    name: iscsi-initiator-utils

- name: Make sure Docker is running
  systemd:
    state: started
    enabled: yes
    name: docker
