- module_defaults:
    hcloud_server:
      token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type }}"
      datacenter: "{{ hetzner_datacenter }}"
      ssh_keys: "{{ hetzner_ssh_keys }}"
  block:
    - hcloud_server:
        name:
          - kube-master
          - kube-worker-1
          - kube-worker-2
          - kube-worker-3

- pause:
    seconds: 60

- name: Refresh inventory
  meta: refresh_inventory
