---
- name: build list of workers
  debug:
    msg: "kube-worker-{{ item }}"
  loop: "{{ range(0, hetzner_worker_count)|list }}"
  register: workernames

- name: set worker list fact
  set_fact:
    workernames: "{{ workernames.results | map(attribute='msg') | list }}"

- name: set kubemaster fact
  set_fact: 
    kubemaster:
      - kube-master

- name: execute hcloud deployment
  module_defaults:
    hcloud_server:
      api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type }}"
      datacenter: "{{ hetzner_datacenter }}"
      ssh_keys: "{{ hetzner_ssh_keys }}"
      state: "{{ hetzner_serverstate }}"
  block:
    - loop: "{{ kubemaster + workernames }}"
      hcloud_server:
        name: "{{ item }}"

- name: wait for server deployment
  pause:
    seconds: 60

- name: Refresh inventory
  meta: refresh_inventory
